version: "3.8"
services:
  project_prochat-redis:
    container_name: project_prochat-redis
    build:
      dockerfile: Dockerfile
      context: ./redis
    image: tztos104/prochat-redis
    ports:
      - "6379:6379"

  project_prochat-database:
    container_name: project_prochat-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: tztos104/project_prochat-database

    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: project_prochat

    volumes:
      - ./database/config:/etc/mysql/conf.d
      - ./database/config:/docker-entrypoint-initdb.d
